version: '3.1'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - ${DB_PORT}

  app:
    restart: always
    build: .
    hostname: app
    environment:
      - PORT=${PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - ${PORT}:${PORT}
      - 9229:9229 # for debugging
    depends_on:
      - postgres

volumes:
  db-data:
